ALTER TABLE outlet_configs
  ADD COLUMN IF NOT EXISTS gps_latitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS gps_longitude DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS gps_radius_meters INTEGER,
  ADD COLUMN IF NOT EXISTS gps_enforcement_enabled BOOLEAN NOT NULL DEFAULT false;
